run:
	go run cmd/main.go --config=../config/app-websocket/app-websocket-local/local.yaml --env=../config/app-websocket/app-websocket-local/.env-local

lint:
	golangci-lint run

# for mocks in future
gen:
	go generate ./...